title: Elastiknn
name: Elastiknn
description: >- # this means to ignore newlines until "baseurl:"
  An Elasticsearch Plugin for Exact and Approximate Nearest Neighbors Search in High Dimensional Vector Spaces
url: "https://alexklibisz.github.io"
baseurl: "/elastiknn"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
author_profile: false

footer:
  links:
    - label: "Github"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/alexklibisz/elastiknn"
    - label: "Twitter"
      icon: "fas fa-fw fa-link"
      url: "https://twitter.com/elastiknn"

plugins:
  - jekyll-feed

exclude:
  - docker-compose.yaml
  - Dockerfile