title: Elastiknn
name: Elastiknn
description: >- # this means to ignore newlines until "baseurl:"
  An Elasticsearch Plugin for Exact and Approximate Nearest Neighbors Search in High Dimensional Vector Spaces
url: "https://elastiknn.com" # the base hostname & protocol for your site, e.g. http://example.com

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
author_profile: false

footer:
  links:
    - label: "Github"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/alexklibisz/elastiknn"
    - label: "Twitter"
      icon: "fas fa-fw fa-link"
      url: "https://twitter.com/elastiknn"

plugins:
  - jekyll-feed

analytics:
  provider: "google"
  google:
    tracking_id: "UA-21164883-1"